#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+TITLE: schoolboy
#+DATE: <2017-07-14 Fri>
#+AUTHOR: Wellesley Shumway
#+EMAIL: wkshumway@Wellesleys-MacBook-Pro.local
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.2.1 (Org mode 9.0.7)
* Boy
** Brad
** Computer Nerd
** 16
** Finding a girl

* Girl
** Tessa
** Not self-concious hippie
** 18
** Hakuna matata


   Friday. A day looked forward to for all teenagers. Some would teenagers might
   get together and play basketball. Some would maybe go to the movies. Some
   might play video games with their friends, and for Brad, his video gaming
   started early Friday. "Uhh, no I don't need that item you go ahead. But if
   Grummel's Pummeler drops I want it!" Brad was playing his favorite game yet:
   World of Warcraft. He could finally play it whenever he wanted too. He had
   saved up enough money over summer to buy his own computer. He loved
   computers. He spent as much time on them as he could. Having his own computer
   in his room allowed him to wake up early before his mom, and play for as long
   as he wanted. He was max level and need to get better gear to enjoy the
   end-game content. In the game, his online friends loved playing with Brad. In
   this virtual world, he felt confident and powerful,
* ...but I guess none of that really mattered; it was time for school.
  Heading straight for his favorite teacher's office, Brad decided not to try to
  finish his English reading before the bell rang. Mr. McChesney was a wonder. He
  wore patterned shirts and bow ties that clashed everyday. But what was special
  about him was his resume of enormous and odd computing accomplishments. Brad
  spent as much time in his office as possible, though that usually only happened
  in the morning. Mr McChesney was always full of stories. Usually, the stories
  were about computing exploits, inventions, or world travel. Today was different.
  Brad had gotten the courage to ask Mr. M how he had ended up in this small town
  high school. It turned out that Mr. M's wife was from here, though Mr. M. was
  from Ireland. Mr. M's wife had loved this place and had always wanted to settle
  down here. It had been her lifelong dream. After she passed away Mr. M carried
  out their retirement plans. Brad had never known that that kind of devotion
  happened to gritty computer people in their old age. He went to the rest of his
  classes, talked to some friends about the ethics of hacking,
* and with that, he went to lunch.
  Lunch time was a special time for Brad. He spent it doing what gave him the
  most satisfaction. He spent it watching Tessa. He quickly rushed over to the
  snack bar and got a salad. If he could do it quickly enough, he could beat the
  rush. Today he was not so fortunate. He got there late and had to endure the
  line. Brad wouldn't mind the line so much, but everyone there just talked
  about boys or girls they were pursuing. He wanted to be with Tessa. She just
  seemed so connected to the real world. Confident and powerful in the real
  world. She didn't need to escape to digital fantasy lands to be happy, she
  just was happy. Brad envied that. He finally got his salad and bread stick and
  headed over to the field to watch Tessa. Without fail she was always there,
  cross-legged and smiling. After he finally sat down, it seemed that moments
  later the bell rang and it was time for class. Class seemed to zoom by. He
  took the bus home and tried to get some homework done. He waited for night to
  fall. He had plans. Plans that were going to happen. He remembered his mom was
  working late that night, so he heated up some mini-pizzas while he waited,
* but finally it came: Friday night
  Tessa was still a mystery. Not only was she not interested in computers, she was
  interested in rocks, trees, birds and mountains. Those things were about as far
  away from computers as you can get. Brad new that she liked beautiful things
  though, and Mr. McChesney always said, "There's nothing more beautiful than an
  elegant algorithm." So he set out to make something that Tessa would thing was
  pretty. At 10, he met her in the park and showed her a graphing program that
  made fractals. She was a little distracted the whole time, but at the end, she
  held his hand. He didn't care about fractals or global supercomputing
  conventions anymore. 
